---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-password
  namespace: ldtteam-firefly
spec:
  encryptedData:
    APP_PASSWORD: AgBxExr/zZmpm9MhNwLUyuaLERxaey7DVzXcS7sxO7/FDA1uFE5SRwhDHMdZ2R0Umve3DwhS0T+2egFp+lMPwU9A8AB7ITf0hRGE6K2/AZc3+EpZM2ctpPJ5j9d8pYJpL8aAyowLOrEr6MbkO/LDYP6vk7zZgYo9N7iJEtikYFpiQmRoXjHqSDaYtOI0tJVTwQk5JNYMTGPchGsx41UMF9YpjwylrGEBWH99Vnj736q9PAdfA331w+a+cw4mn3CnOiiWPwZpNODdOrQo7kBvXxel0jfgA2CnnWI01bhxYeaVZFpwgP+0Zqe/3YjJOARVYp8HbyGj8lN/06B2HhcFmG7BIVFD6kRZjyi3cv/VExZ1vMEznn+5EnQVgSngc5VmX4aBYUPShqm+TwkkxFX8rv/AUXy7e6BlCQzAwvjmBuAsabNHd0QuDrZdg+fHQ1GKxyHf4miHig8ZfwkXXjhCiFZvsxZW+BHcdCb1XrfEY+Fv9AEOwl3voTTtwTYeKU6Aw4+oFxxXLDX5/rOLHWY9s1JTKIesojQQnD+LTUMXAXOzsV36NKHF93pCw16rEdfhNTNKiD91YmJbgio9LD1au7PbzaMscjpF4intWomDl0HxUYLMUDP6bsbu5hk9EXzEu/wE+nq40egTYlzTX12MkqR0omi0q04SFLQUhWaKtFiCYuZxBQO7MnTh33cT1MwcfHq05+A7x6857Yz5YQazVLKTl9je1g==
  template:
    metadata:
      name: app-password
      namespace: ldtteam-firefly
      labels:
        app.kubernetes.io/part-of: firefly-finance-manager
