apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: donator-auth-ha
  namespace: argocd
spec:
  project: ldtteam
  destination:
    server: "https://kubernetes.default.svc"
    namespace: minecolonies-donator-auth
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://ldtteam.github.io/authentication
      chart: ldtteam-authentication-server
      targetRevision: "0.5.*"
      helm:
        releaseName: donator-auth
        valuesObject:
          ingress:
            hostname: auth-ha.minecolonies.com
          environment:
            LDTTEAM_AUTH_ConnectionStrings__postgres: Server=donator-auth-postgresql.donator-auth.svc.cluster.local;Port=5432;User Id=ldtteam-donator-auth;Password=DonatorAuth1!;Database=authentication;
          postgresql:
            enabled: false
          postgresha:
            enabled: false

    - repoURL: {{ .Values.repository.url }}
      path: ldtteam-charts/donator-auth-extras
      targetRevision: HEAD
      helm:
