apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: donator-auth-ha
  namespace: argocd
spec:
  project: ldtteam
  destination:
    server: "https://kubernetes.default.svc"
    namespace: minecolonies-donator-auth
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://ldtteam.github.io/authentication
      chart: ldtteam-authentication-server
      targetRevision: "0.5.*"
      helm:
        releaseName: donator-auth
        valuesObject:
          replicaCount: 0
          ingress:
            hostname: auth-ha.minecolonies.com
            annotations:
              external-dns.alpha.kubernetes.io/target: cluster.ldtteam.com
          environment:
            LDTTEAM_AUTH_ConnectionStrings__postgres: Server=donator-auth-postgresha-pgpool.mineclonies-donator-auth.svc.cluster.local;Port=5432;User Id=postgres;Password=DonatorAuth1!;Database=authentication;
            LDTTEAM_AUTH_ConnectionStrings__postgres_github: Server=donator-auth-postgresha-pgpool.mineclonies-donator-auth.svc.cluster.local;Port=5432;User Id=postgres;Password=DonatorAuth1!;Database=github;
            LDTTEAM_AUTH_ConnectionStrings__postgres_patreon: Server=donator-auth-postgresha-pgpool.mineclonies-donator-auth.svc.cluster.local;Port=5432;User Id=postgres;Password=DonatorAuth1!;Database=patreon;
          postgresql:
            enabled: false
          postgresha:
            enabled: true

    - repoURL: {{ .Values.repository.url }}
      path: ldtteam-charts/donator-auth-extras
      targetRevision: HEAD
      helm:
