apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ldtteam-firefly
  namespace: argocd
spec:
  project: ldtteam
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ldtteam-firefly
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://firefly-iii.github.io/kubernetes/
      chart: firefly-iii-stack
      targetRevision: "0.*"
      helm:
        releaseName: ldtteam-finance-manager
        valuesObject:
          firefly-db:
            storage:
              accessModes: ReadWriteOnce
              dataSize: 20Gi

          firefly-iii:
            config:
              env:
                TZ: "Europe/Berlin"
              existingSecret: app-password
            persistence:
              storage: 20Gi
            ingress:
              enabled: true
              className: nginx
              hosts:
                - finances.ldtteam.com
              tls:
                - secretName: firefly-tls
                  hosts:
                    - finances.ldtteam.com
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt-dns
                nginx.ingress.kubernetes.io/ssl-redirect: "true"
                external-dns.alpha.kubernetes.io/target: "cluster.ldtteam.com"

    - repoURL: {{ .Values.repository.url }}
      path: ldtteam-charts/firefly-finance-manager-extras
      targetRevision: HEAD
      helm: