apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecolonies-wiki
  namespace: argocd
spec:
  project: ldtteam
  destination:
    server: "https://kubernetes.default.svc"
    namespace: minecolonies-wiki
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://ldtteam.github.io/MinecoloniesWiki
      chart: website
      targetRevision: "0.*"
      helm:
        releaseName: minecolonies-wiki
